import type { AssetProvenance } from './assetManifest'
import type { AssetKind, AssetRequirement } from './gameSpec'

/**
 * Phase 5 provider-adapter contract. Providers are pure: generated bytes are
 * a function of the requirement and provider context only. The orchestrator
 * owns path construction, while one shared style context keeps a game's
 * generated asset family coherent.
 */
export interface StyleParams {
  palette: {
    baseHue: number
    accentHues: number[]
    saturation: number
    lightness: number
  }
  audio: {
    waveform: 'sine' | 'triangle' | 'square'
    tempo: 'slow' | 'mid' | 'brisk'
  }
}

export interface ProviderContext {
  /** Per-asset child seed derived by the orchestrator, not the game seed. */
  seed: number
  style: StyleParams
  specVersion: number
}

export interface GeneratedBytes {
  bytes: Uint8Array
  provenance: AssetProvenance
}

export interface AssetProvider {
  id: string
  version: string
  /** Stable identity for output-affecting configuration used by guarded caches. */
  cacheKey?: string
  kinds: readonly AssetKind[]
  fileExtension(requirement: AssetRequirement): string
  generate(requirement: AssetRequirement, ctx: ProviderContext): Promise<GeneratedBytes>
}

export type { AssetKind, AssetRequirement }
