import type { GameSpec } from '@automata/contracts'

/** Deterministic spec-to-markdown design brief for the human checkpoint. */
export function renderDesignBrief(spec: GameSpec): string {
  const lines: string[] = []
  const push = (line = ''): void => { lines.push(line) }

  push(`# ${spec.identity.title} — Design Brief`)
  push()
  push(`> ${spec.identity.logline}`)
  push()
  push(`- **Game:** \`${spec.identity.id}\` · specVersion ${spec.specVersion} · rated ${spec.identity.contentRating}`)
  push(`- **Themes:** ${spec.identity.themes.join(', ')}`)
  push(`- **Prompt:** ${spec.provenance.prompt}`)
  push()
  push('## Direction')
  push()
  push(`- **Visual:** ${spec.direction.visualStyle}`)
  push(`- **Audio:** ${spec.direction.audioStyle}`)
  push(`- **Dialogue tone:** ${spec.direction.dialogueTone}`)
  push(`- **Camera:** ${spec.direction.camera}`)
  push()
  push('## Supported translations')
  push()
  if (spec.provenance.translations.length === 0) {
    push('No unsupported requests were translated.')
  } else {
    for (const translation of spec.provenance.translations) {
      push(`- Requested **${translation.requested}** → **${translation.translatedTo}** (${translation.reason})`)
    }
  }
  push()
  push('## World')
  push()
  for (const location of spec.world.locations) push(`- **${location.name}** (${location.kind}): ${location.description}`)
  push()
  push('## Cast')
  push()
  for (const character of spec.cast) push(`- **${character.name}** (${character.role}): ${character.description}`)
  push()
  push('## Story outline')
  push()
  push(spec.story.premise)
  push()
  for (const beat of spec.story.beats) push(`1. *${beat.kind}* — ${beat.summary}`)
  push()
  push('## Quest outline')
  push()
  for (const quest of spec.story.quests) push(`- **${quest.kind}:** ${quest.summary}`)
  push()
  push('## Capabilities')
  push()
  for (const capability of spec.capabilities) push(`- \`${capability.id}\`${capability.requirements.length ? ` — needs: ${capability.requirements.join('; ')}` : ''}`)
  push()
  push('## Budgets')
  push()
  for (const [key, value] of Object.entries(spec.budgets)) push(`- ${key}: ${value}`)
  push()
  push('## Progression')
  push()
  for (const milestone of spec.progression.milestones) push(`1. ${milestone.summary}`)
  push()
  push('## Asset requirements')
  push()
  for (const asset of spec.assets) push(`- \`${asset.id}\` (${asset.kind}): ${asset.description}`)
  push()
  push('## Acceptance criteria')
  push()
  for (const criterion of spec.acceptance) push(`- [${criterion.kind}] ${criterion.description} → \`${criterion.target}\``)
  push()
  push('## Version history')
  push()
  for (const entry of spec.provenance.history) push(`- v${entry.version}: ${entry.reason}`)
  push()
  return lines.join('\n')
}
