/** Generated workspace config, entry HTML, and README. */

export function packageJson(name: string, port: number): string {
  return `${JSON.stringify({
    name,
    private: true,
    version: '0.0.0',
    type: 'module',
    exports: {
      '.': './src/index.ts',
      './project': './src/project/index.ts',
      './editor': './src/project/editor.ts'
    },
    dependencies: {
      '@automata/editor': '*',
      '@automata/engine': '*',
      '@automata/game-kit': '*',
      '@automata/project': '*'
    },
    devDependencies: { tsx: '^4.20.0' },
    scripts: {
      dev: 'vite',
      'validate:project': 'node --import tsx scripts/validate-project.ts',
      'generate:project': 'node --import tsx scripts/generate-project.ts',
      build: 'npm run validate:project && vite build',
      typecheck: 'tsc --noEmit'
    },
    automata: { devPort: port }
  }, null, 2)}\n`
}

export function tsconfigJson(): string {
  return `${JSON.stringify({
    extends: '../../tsconfig.base.json',
    compilerOptions: { lib: ['ES2022', 'DOM', 'DOM.Iterable'] },
    include: ['src', 'tests', 'scripts', 'vitest.config.ts']
  }, null, 2)}\n`
}

export function viteConfigTs(): string {
  return `import { readFileSync } from 'node:fs'
import { defineConfig } from 'vite'

const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8')) as {
  automata: { devPort: number }
}

export default defineConfig({
  base: './',
  server: { host: '127.0.0.1', port: pkg.automata.devPort, strictPort: true }
})
`
}

export function vitestConfigTs(name: string): string {
  return `import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: { name: '${name}', environment: 'happy-dom', include: ['tests/**/*.test.ts'] }
})
`
}

export function indexHtml(label: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <title>${label}</title>
    <style>
      body { margin: 0; background: #05070f; color: #e8ecff; font-family: system-ui, sans-serif; }
      canvas { display: block; width: 100vw; height: 100vh; }
      .hud { position: fixed; top: 12px; left: 12px; padding: 6px 10px; background: rgba(5, 7, 15, 0.7); border-radius: 6px; }
    </style>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`
}

export function readmeMd(name: string, label: string, port: number): string {
  return `# ${label}

A minimal registered AutomataEngine game: steer the keeper (WASD/arrows) to the
beacon before the time limit. Generated by \`npm run new-game\` as a working
starting point — every layer below is meant to be replaced with your game.

## Architecture

- \`src/sim/sim.ts\` — pure fixed-step simulation. No DOM, clocks, or RNG; the
  same inputs always produce the same run, which is what makes headless
  evaluation and agent-driven tuning possible.
- \`src/game/gameplay.ts\` — wires the sim to the engine render port; shared by
  the browser boot and the editor's live preview.
- \`src/project/\` — the authoring surface: schemas, template, validation,
  compilation, evaluation, and the registry loader entries
  (\`loadEditorRegistration\`, \`loadHeadlessRegistration\`). Because these
  exist, this game appears in the level-editor chooser and the MCP server
  without any wiring elsewhere.
- \`src/main.ts\` — thin browser composition root (excluded from coverage).

## Commands

From the repository root:

\`\`\`bash
npm run dev -w ${name}            # play at http://127.0.0.1:${port}
npx vitest run --project ${name}  # unit tests
npm run typecheck -w ${name}
npm run build -w ${name}          # validates the project, then builds
PLAYWRIGHT_ONLY=${name} npx playwright test games/${name}/e2e
\`\`\`

## Authoring content

The authored project lives in \`public/project\` (manifest, scenes, resources).
Three equivalent ways to change it:

1. Edit \`src/project/template.ts\`, then \`npm run generate:project -w ${name}\`
   to regenerate \`public/project\`. The content test keeps both in sync.
2. Open it in the editor: \`npm run dev:editor\`, choose ${label}.
3. Let an agent edit it over MCP:
   \`node_modules/.bin/automata-editor-mcp --project games/${name}/public/project\`
   exposes typed add/set/validate/evaluate tools.

\`npm run build -w ${name}\` refuses to ship an invalid project.
`
}
